<?xml version="1.0" encoding="UTF-8"?>
<testng-results total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-06-03T07:04:35Z" name="Default suite" finished-at="2023-06-03T07:04:39Z" duration-ms="4350">
    <groups>
    </groups>
    <test started-at="2023-06-03T07:04:35Z" name="Default test" finished-at="2023-06-03T07:04:39Z" duration-ms="4350">
      <class name="com.example.testing.Day7_5">
        <test-method signature="executeURL()[pri:0, instance:com.example.testing.Day7_5@13cd7ea5]" started-at="2023-06-03T12:34:35Z" name="executeURL" finished-at="2023-06-03T12:34:39Z" duration-ms="4328" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Domain Names, Websites, Hosting & Online Marketing Tools - GoDaddy IN] but found [Domain Names, Websites, Hosting & Online Marketing Tools - GoDaddy]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Domain Names, Websites, Hosting & Online Marketing Tools - GoDaddy IN] but found [Domain Names, Websites, Hosting & Online Marketing Tools - GoDaddy]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.example.testing.Day7_5.executeURL(Day7_5.java:19)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- executeURL -->
      </class> <!-- com.example.testing.Day7_5 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
